import random

# This function defines that a random number would be generated by computer and you need to find it out!


def guess(x):
    random_number = random.randint(1, x)
    guess = 0
    while guess != random_number:
        guess = int(input(f'Guess the number between 1 to {x}: '))
        if guess < random_number:
            print("sorry! guess again. Too low.")
        elif guess > random_number:
            print("sorry! guess again. Too high.")
    print(
        f"yay, congrats. You have guessed the number {random_number} correctly!")


# This function defines that your guessed number would now be guessed by the computer
def computer_guess(x):
    low = 1
    high = x
    feedback = ''
    while feedback != 'c':
        if low != high:
            guess = random.randint(low, high)
        else:
            guess = low  # could also be high b/c low = high
        feedback = input(
            f"Is {guess} too high (H), too low (L), or correct (c)?? ")
        if feedback == 'h':
            high = guess - 1
        elif feedback == 'l':
            low = guess + 1

    print(f"yay, computer have guessed the number, {guess} correctly")


computer_guess(5)
